"""Service application factory: construct FastAPI apps consistently across services.

Independent domain entry points (realmock.domains.prep / realmock.domains.interview) share the same
CORS / health / route-prefix / exception-handler / trace_id assembly logic; this factory removes literal duplication.

Every app built by this factory is fully assembled to run as an independent process:

- Unified exception handlers (error responses use the same envelope);
- trace_id injection middleware (observability in every process);
- CORS / health / ``/api/v1`` prefix;
- Support for one or multiple routers (reserved for a future "multiple services in one process" setup).

The aggregate entry point (realmock.asgi) has its own heavier assembly (production gate / ``/api`` compatibility alias)
and intentionally does not reuse this factory—the two mount their own routes without interfering with each other.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable, Sequence
from contextlib import asynccontextmanager
from typing import Any

from fastapi import APIRouter, FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from starlette.exceptions import HTTPException as StarletteHTTPException

from realmock.platform.config import get_settings
from realmock.platform.core.constants import TRACE_ID_HEADER
from realmock.platform.core.error_handlers import (
    on_http_exception,
    on_request_validation,
    on_starlette_http_exception,
    on_unhandled_exception,
    on_unsafe_url,
)
from realmock.platform.core.local_only import LOCAL_API_DEPENDENCIES
from realmock.platform.core.logging import get_trace_id, reset_trace_id, set_trace_id
from realmock.platform.core.security import UnsafeURLError

logger = logging.getLogger(__name__)

# X-Request-Id validation: only [A-Za-z0-9_-]{8,64} is allowed. Values containing other characters / that are too short / that are too long are always regenerated
# Regenerate to prevent log injection (CRLF / control characters). Keep the same rules as the asgi aggregation entry.
_REQUEST_ID_RE = re.compile(r"^[A-Za-z0-9_\-]{8,64}$")


def _sanitize_request_id(raw: str | None) -> str | None:
    """Returns the original value if the verification passes, otherwise returns None (regenerated by set_trace_id)."""
    if raw and _REQUEST_ID_RE.match(raw):
        return raw
    return None


def create_service_app(
    *,
    service_routers: APIRouter | Sequence[APIRouter],
    title: str,
    description: str,
    service_name: str,
    lifespan_startup: Callable[[], Any] | None = None,
    register_error_handlers: bool = True,
    enable_trace: bool = True,
) -> FastAPI:
    """Construct a service FastAPI app (CORS + health + /api/v1 routes + exception handlers + trace).

    Args:
        service_routers: The service's plain route aggregate (without a prefix; this function injects /api/v1);
            supports one ``APIRouter`` or several (reserved for combining multiple services in one process).
        title: FastAPI title
        description: FastAPI description
        service_name: service field returned by ``/health`` (such as "api-service")
        lifespan_startup: optional startup hook (table creation/migrations/RAG, etc.); skipped when TEST_MODE=1
        register_error_handlers: register unified exception handlers (True by default), ensuring error responses
            from independent processes use the shared envelope
        enable_trace: inject trace_id middleware (True by default), ensuring observability for independent processes
    """
    settings = get_settings()

    # Normalized router list (compatible with single APIRouter and multiple)
    routers: list[APIRouter] = (
        [service_routers]
        if isinstance(service_routers, APIRouter)
        else list(service_routers)
    )

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        import os

        if os.environ.get("TEST_MODE") == "1":
            yield
            return
        if lifespan_startup is not None:
            import inspect

            result = lifespan_startup()
            if inspect.isawaitable(result):
                await result
        yield

    app = FastAPI(
        title=title,
        description=description,
        version="1.0.0",
        lifespan=lifespan,
    )

    if enable_trace:
        install_trace_middleware(app)

    add_default_cors(app, cors_origin_list=settings.cors_origin_list)

    # Local access control is declared uniformly at the mount layer: covering all service routes; /health, etc. are here
    # Endpoints registered outside of the mount layer (e.g. /health) stay public.
    for r in routers:
        app.include_router(r, prefix="/api/v1", dependencies=LOCAL_API_DEPENDENCIES)

    if register_error_handlers:
        register_core_error_handlers(app)

    @app.get("/health")
    def health():
        return {"status": "ok", "service": service_name, "version": "1.0.0"}

    return app


def install_trace_middleware(app: FastAPI) -> None:
    """Install the trace_id injection middleware (the X-Request-Id verification rule has a single truth and the aggregation entry is shared)."""

    @app.middleware("http")
    async def trace_middleware(request: Request, call_next):
        """Inject trace_id for each HTTP request to facilitate log concatenation."""
        raw = request.headers.get("x-request-id") or request.headers.get("X-Request-Id")
        token = set_trace_id(_sanitize_request_id(raw))
        response_trace_id = get_trace_id()
        try:
            response = await call_next(request)
        except Exception:
            logger.exception("HTTP middleware exception path=%s", request.url.path)
            raise
        finally:
            reset_trace_id(token)
        response.headers[TRACE_ID_HEADER] = response_trace_id or ""
        return response


def add_default_cors(app: FastAPI, *, cors_origin_list: list[str]) -> None:
    """Install a unified CORS policy (method/header list and aggregation entry share the same one)."""
    app.add_middleware(
        CORSMiddleware,
        allow_origins=cors_origin_list,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "X-Request-Id", TRACE_ID_HEADER, "X-Interview-Token"],
        expose_headers=[TRACE_ID_HEADER],
        max_age=600,
    )


def register_core_error_handlers(app: FastAPI) -> None:
    """Register 5 handlers for a unified error response envelope (single truth)."""
    app.add_exception_handler(RequestValidationError, on_request_validation)  # type: ignore[arg-type]
    app.add_exception_handler(HTTPException, on_http_exception)  # type: ignore[arg-type]
    app.add_exception_handler(StarletteHTTPException, on_starlette_http_exception)  # type: ignore[arg-type]
    app.add_exception_handler(UnsafeURLError, on_unsafe_url)  # type: ignore[arg-type]
    app.add_exception_handler(Exception, on_unhandled_exception)
