"""Prep HTTP contract: request/response schemas for the interview-preparation domain."""

from __future__ import annotations

from realmock.domains.prep.schemas.prep import (
    MEMORY_ORIGINS,
    PrepArchiveRequest,
    PrepArchiveResponse,
    PrepAskEvent,
    PrepAskQuestion,
    PrepCompactRequest,
    PrepCompactResponse,
    PrepContextBucket,
    PrepContextResponse,
    PrepCreateRequest,
    PrepDeletedResponse,
    PrepForkRequest,
    PrepForkResponse,
    PrepHistoryMessage,
    PrepLinkRequest,
    PrepLinkResponse,
    PrepMemoryBatchDelete,
    PrepMemoryCreate,
    PrepMemoryDetail,
    PrepMemorySummary,
    PrepMemoryTagsResponse,
    PrepMemoryUpdate,
    PrepMessageRequest,
    PrepMessageResponse,
    PrepPurgeAllRequest,
    PrepSessionCreateResponse,
    PrepSessionSummary,
    PrepSuggestionsRequest,
    PrepSuggestionsResponse,
    PrepSummaryUpdateRequest,
    PrepTruncateRequest,
    PrepTruncateResponse,
)
from realmock.platform.schemas import ResumePickerItem

__all__ = [
    "MEMORY_ORIGINS",
    "PrepAskEvent",
    "PrepAskQuestion",
    "PrepArchiveRequest",
    "PrepArchiveResponse",
    "PrepCompactRequest",
    "PrepCompactResponse",
    "PrepContextBucket",
    "PrepContextResponse",
    "PrepDeletedResponse",
    "PrepCreateRequest",
    "PrepForkRequest",
    "PrepForkResponse",
    "PrepHistoryMessage",
    "PrepLinkRequest",
    "PrepLinkResponse",
    "PrepMemoryBatchDelete",
    "PrepMemoryCreate",
    "PrepMemoryDetail",
    "PrepMemorySummary",
    "PrepMemoryTagsResponse",
    "PrepMemoryUpdate",
    "PrepMessageRequest",
    "PrepMessageResponse",
    "PrepPurgeAllRequest",
    "PrepSessionCreateResponse",
    "PrepSessionSummary",
    "PrepSuggestionsRequest",
    "PrepSuggestionsResponse",
    "PrepSummaryUpdateRequest",
    "PrepTruncateRequest",
    "PrepTruncateResponse",
    "ResumePickerItem",
]
