"""Prep HTTP contract: request/response schemas for the interview-preparation domain."""

from __future__ import annotations

from realmock.platform.schemas import ResumePickerItem

from realmock.domains.prep.schemas.prep import (
    COMPACTION_INTENSITIES,
    DIRECTIVE_MAX_CHARS,
    MEMORY_ORIGINS,
    RETAIN_MAX,
    RETAIN_MIN,
    PrepArchiveRequest,
    PrepCompactRequest,
    PrepCompactResponse,
    PrepContextBucket,
    PrepContextResponse,
    PrepCreateRequest,
    PrepForkRequest,
    PrepForkResponse,
    PrepHistoryMessage,
    PrepLinkRequest,
    PrepMemoryBatchDelete,
    PrepMemoryCreate,
    PrepMemoryDetail,
    PrepMemorySummary,
    PrepMemoryUpdate,
    PrepMessageRequest,
    PrepMessageResponse,
    PrepSessionCreateResponse,
    PrepSessionSummary,
    PrepSummaryUpdateRequest,
    PrepTruncateRequest,
)

__all__ = [
    "COMPACTION_INTENSITIES",
    "DIRECTIVE_MAX_CHARS",
    "MEMORY_ORIGINS",
    "RETAIN_MAX",
    "RETAIN_MIN",
    "PrepArchiveRequest",
    "PrepCompactRequest",
    "PrepCompactResponse",
    "PrepContextBucket",
    "PrepContextResponse",
    "PrepCreateRequest",
    "PrepForkRequest",
    "PrepForkResponse",
    "PrepHistoryMessage",
    "PrepLinkRequest",
    "PrepMemoryBatchDelete",
    "PrepMemoryCreate",
    "PrepMemoryDetail",
    "PrepMemorySummary",
    "PrepMemoryUpdate",
    "PrepMessageRequest",
    "PrepMessageResponse",
    "PrepSessionCreateResponse",
    "PrepSessionSummary",
    "PrepSummaryUpdateRequest",
    "PrepTruncateRequest",
    "ResumePickerItem",
]
